/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif


void delay();


int main(void)
{
	uint32_t volatile *const RCC_AHB1ENR = (uint32_t*)(0x40023800 + 0x30);
	uint32_t volatile *const GPIOC_MODER = (uint32_t*)(0x40020800);
	uint32_t volatile *const GPIOC_PUPDR = (uint32_t*)(0x40020800 + 0x0C);
	uint32_t volatile *const GPIOC_IDR = (uint32_t*)(0x40020800 +  0x10);
	uint32_t volatile *const GPIsOC_ODR = (uint32_t*)(0x40020800 + 0x14);

	*RCC_AHB1ENR |= (1 << 2);

	*GPIOC_MODER |= (1 << 20);
	*GPIOC_MODER |= (1 << 22);
	*GPIOC_MODER |= (1 << 24);
	*GPIOC_MODER |= (1 << 26);

	*GPIOC_PUPDR |= (1);
	*GPIOC_PUPDR |= (1 << 2);
	*GPIOC_PUPDR |= (1 << 4);
	*GPIOC_PUPDR |= (1 << 6);

	*GPIOC_ODR |= (1 << 10);
	*GPIOC_ODR |= (1 << 11);
	*GPIOC_ODR |= (1 << 12);
	*GPIOC_ODR |= (1 << 13);
    /* Loop forever */
	while(1){
		// checking the first row:
		*GPIOC_ODR &= ~(1 << 10);
		*GPIOC_ODR |= (1 << 11);
		*GPIOC_ODR |= (1 << 12);
		*GPIOC_ODR |= (1 << 13);
		if (!(*GPIOC_IDR & (1 << 0))){
			delay();
			printf("KEY 1 is pressed!\n");
		}
		else if (!(*GPIOC_IDR & (1 << 1))){
			delay();
			printf("KEY 2 is pressed!\n");
		}
		else if (!(*GPIOC_IDR & (1 << 2))){
			delay();
			printf("KEY 3 is pressed!\n");
		}
		else if (!(*GPIOC_IDR & (1 << 3))){
			delay();
			printf("KEY A is pressed!\n");
		}
		// checking the second row:
		*GPIOC_ODR |= (1 << 10);
		*GPIOC_ODR &= ~(1 << 11);
		*GPIOC_ODR |= (1 << 12);
		*GPIOC_ODR |= (1 << 13);
		if (!(*GPIOC_IDR & (1 << 0))){
			delay();
			printf("KEY 4 is pressed!\n");
		}
		else if (!(*GPIOC_IDR & (1 << 1))){
			delay();
			printf("KEY 5 is pressed!\n");
		}
		else if (!(*GPIOC_IDR & (1 << 2))){
			delay();
			printf("KEY 6 is pressed!\n");
		}
		else if (!(*GPIOC_IDR & (1 << 3))){
			delay();
			printf("KEY B is pressed!\n");
		}
		// checking the third row:
		*GPIOC_ODR |= (1 << 10);
		*GPIOC_ODR |= (1 << 11);
		*GPIOC_ODR &= ~(1 << 12);
		*GPIOC_ODR |= (1 << 13);
		if(!(*GPIOC_IDR & (1 << 0))){
			delay();
			printf("KEY 7 is pressed!\n");
		}
		else if (!(*GPIOC_IDR & (1 << 1))){
			delay();
			printf("KEY 8 is pressed!\n");
		}
		else if (!(*GPIOC_IDR & (1 << 2))){
			delay();
			printf("KEY 9 is pressed!\n");
		}
		else if (!(*GPIOC_IDR & (1 << 3))){
			delay();
			printf("KEY C is pressed!\n");
		}
		// checking the last one row:
		*GPIOC_ODR |= (1 << 10);
		*GPIOC_ODR |= (1 << 11);
		*GPIOC_ODR |= (1 << 12);
		*GPIOC_ODR &= ~(1 << 13);
		if(!(*GPIOC_IDR & (1 << 0))){
			delay();
			printf("KEY * is pressed!\n");
		}
		else if (!(*GPIOC_IDR & (1 << 1))){
			delay();
			printf("KEY 0 is pressed!\n");
		}
		else if (!(*GPIOC_IDR & (1 << 2))){
			delay();
			printf("KEY # is pressed!\n");
		}
		else if (!(*GPIOC_IDR & (1 << 3))){
			delay();
			printf("KEY D is pressed!\n");
		}
	}
}


void delay(){
	for(int i = 0; i < 300000; i++){
		continue;
	}
}
