/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include <stdio.h>
#include "main.h"


#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

void delay();

int main(void)
{
	printf("Hello world\n");;
	RCC_AHB1ENR_t volatile *const rcc_ahb1enr = (RCC_AHB1ENR_t*)(0x40023800 + 0x30);
	rcc_ahb1enr->gpioa_en = 1;
	rcc_ahb1enr->gpiob_en = 1;
	rcc_ahb1enr->gpioc_en = 1;

	GPIOx_MODER_t volatile *const gpioa_moder = (GPIOx_MODER_t*)(0x40020000);
	GPIOx_MODER_t volatile *const gpiob_moder = (GPIOx_MODER_t*)(0x40020400);
	GPIOx_MODER_t volatile *const gpioc_moder = (GPIOx_MODER_t*)(0x40020800);

	gpioc_moder->MODER6 = 1;
	gpioc_moder->MODER5 = 1;
	gpioa_moder->MODER10 = 1;
	gpioa_moder->MODER8 = 0;
	gpioc_moder->MODER4 = 1;
	gpiob_moder->MODER5 = 0;
	gpiob_moder->MODER4 = 0;
	gpiob_moder->MODER10 = 0;

	GPIOx_PUPDR_t volatile *const gpioa_pupdr = (GPIOx_PUPDR_t*)(0x40020000 +  0x0C);
	GPIOx_PUPDR_t volatile *const gpiob_pupdr = (GPIOx_PUPDR_t*)(0x40020400 +  0x0C);
	GPIOx_PUPDR_t volatile *const gpioc_pupdr = (GPIOx_PUPDR_t*)(0x40020800 +  0x0C);

	gpioc_pupdr->MODER6 = 0;
	gpioc_pupdr->MODER5 = 0;
	gpioa_pupdr->MODER10 = 0;
	gpioa_pupdr->MODER8 = 1;
	gpioc_pupdr->MODER4 = 0;
	gpiob_pupdr->MODER5 = 1;
	gpiob_pupdr->MODER4 = 1;
	gpiob_pupdr->MODER10 = 1;

	// R4 = PC6
	// R3 = PC5
	// R2 = PA10
	// R1 = PC4

	// C1 = PB5
	// C2 = PB4
	// C3 = PB10
	// C4 = PA8

	GPIOx_IDR_t volatile *const gpioa_idr = (GPIOx_IDR_t*)(0x40020000 + 0x10);
	GPIOx_IDR_t volatile *const gpiob_idr = (GPIOx_IDR_t*)(0x40020400 + 0x10);
	// GPIOx_IDR_t volatile *const gpioc_idr = (GPIOx_IDR_t*)(0x40020800 + 0x10);




	GPIOx_ODR_t volatile *const gpioa_odr = (GPIOx_ODR_t*)(0x40020000 + 0x14);
	// GPIOx_ODR_t volatile *const gpiob_odr = (GPIOx_ODR_t*)(0x40020400 + 0x14);
	GPIOx_ODR_t volatile *const gpioc_odr = (GPIOx_ODR_t*)(0x40020800 + 0x14);

    /* Loop forever */
	printf("Enabling the Keypad 4x4!\n");
	fflush(stdout);
	while(1){
		// Checking first row
		gpioc_odr->P4 = 0;
		gpioa_odr->P10 = 1;
		gpioc_odr->P5 = 1;
		gpioc_odr->P6 = 1;
		if(!gpiob_idr->P5){
			printf("1\n");
			delay();
		}
		else if(!gpiob_idr->P4){
			printf("2\n");
			delay();
		}
		else if(!gpiob_idr->P10){
			printf("3\n");
			delay();
		}
		else if(!gpioa_idr->P8){
			printf("A\n");
			delay();
		}


		gpioc_odr->P4 = 1;
		gpioa_odr->P10 = 0;
		gpioc_odr->P5 = 1;
		gpioc_odr->P6 = 1;

		if(!gpiob_idr->P5){
			printf("4\n");
			delay();
		}
		else if(!gpiob_idr->P4){
			printf("5\n");
			delay();
		}
		else if(!gpiob_idr->P10){
			printf("6\n");
			delay();
		}
		else if(!gpioa_idr->P8){
			printf("B\n");
			delay();
		}


		gpioc_odr->P4 = 1;
		gpioa_odr->P10 = 1;
		gpioc_odr->P5 = 0;
		gpioc_odr->P6 = 1;

		if(!gpiob_idr->P5){
			printf("7\n");
			delay();
		}
		else if(!gpiob_idr->P4){
			printf("8\n");
			delay();
		}
		else if(!gpiob_idr->P10){
			printf("9\n");
			delay();
		}
		else if(!gpioa_idr->P8){
			printf("C\n");
			delay();
		}


		gpioc_odr->P4 = 1;
		gpioa_odr->P10 = 1;
		gpioc_odr->P5 = 1;
		gpioc_odr->P6 = 0;;

		if(!gpiob_idr->P5){
			printf("*\n");
			delay();
		}
		else if(!gpiob_idr->P4){
			printf("0\n");
			delay();
		}
		else if(!gpiob_idr->P10){
			printf("#\n");
			delay();
		}
		else if(!gpioa_idr->P8){
			printf("D\n");
			delay();
		}
	}
}


void delay(){
	for(uint32_t i = 0; i < 400000; i++);
}
