/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */




#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include <stdint.h>
#include <stdio.h>
#include "main.h"
#include "led.h"


void task1_handler(void);
void task2_handler(void);
void task3_handler(void);
void task4_handler(void);
void init_systick_timer(uint32_t tick_hz);
__attribute__((naked)) void init_scheduler_stack(uint32_t sched_top_of_stack);

void init_tasks_stack(void);

uint32_t get_psp_value(void);

__attribute__((naked)) void switch_sp_to_psp(void);

void enable_processor_faults(void);

void SysTick_Handler(void);

void save_psp_value(uint32_t current_psp_value);

void HardFault_Handler(void);
void MemManage_Handler(void);
void BusFault_Handler(void);

void task_delay(uint32_t tick_count);

__attribute__((naked)) void PendSV_Handler(void);

// some stack memory calculations:

uint32_t current_task = 1;

uint32_t g_tick_count = 0;

typedef struct{
	uint32_t psp_value;
	uint32_t block_count;
	uint8_t current_state;
	void(*task_handler)(void);
}TCB_t;

TCB_t user_tasks[MAX_TASKS];


int main(void)
{
	enable_processor_faults();

	init_scheduler_stack(SCHED_STACK_START);

	init_tasks_stack();

	init_systick_timer(TICK_HZ);

	switch_sp_to_psp();

	init_leds();

	task1_handler();

	while(1){

	}
}


void idle_handler(){
	while(1);
}



void task1_handler(void){
	while(1){
		led_on(RED_LED);
		task_delay(DELAY_250_MS);
		led_off(RED_LED);
		task_delay(DELAY_250_MS);
	}
}


void task2_handler(void){
	while(1){
		led_on(GREEN_LED);
		task_delay(DELAY_500_MS);
		led_off(GREEN_LED);
		task_delay(DELAY_500_MS);
	}
}


void task3_handler(void){
	while(1){
		led_on(YELLOW_LED);
		task_delay(DELAY_750_MS);
		led_off(YELLOW_LED);
		task_delay(DELAY_750_MS);
	}
}


void task4_handler(void){
	while(1){
		led_on(BLUE_LED);
		task_delay(DELAY_1000_MS);
		led_off(BLUE_LED);
		task_delay(DELAY_1000_MS);
	}
}


void init_systick_timer(uint32_t tick_hz){
	uint32_t *pSYST_RVR = (uint32_t*)0xE000E014;
	uint32_t count_value = (SYSTICK_TIM_CLK / tick_hz) - 1;
	// clear the value of SVR
	*pSYST_RVR &= ~(0x00FFFFFF);
	// load the reload value
	*pSYST_RVR |= count_value;
	// do some settings
	uint32_t *pSYST_CSR = (uint32_t*)0xE000E010;
	*pSYST_CSR |= (1 << 1); // enable systick exception request
	*pSYST_CSR |= (1 << 2); // indicates processor clock source
	*pSYST_CSR |= (1 << 0); // enables the counter
	// enable the systick
}


__attribute__((naked)) void init_scheduler_stack(uint32_t sched_top_of_stack){
	__asm volatile("MSR MSP, R0");
	__asm volatile("BX LR");
}


void init_tasks_stack(void){

	user_tasks[0].current_state = TASK_READY_STATE;
	user_tasks[1].current_state = TASK_READY_STATE;
	user_tasks[2].current_state = TASK_READY_STATE;
	user_tasks[3].current_state = TASK_READY_STATE;
	user_tasks[4].current_state = TASK_READY_STATE;


	user_tasks[0].psp_value = IDLE_STACK_START;
	user_tasks[1].psp_value = T1_STACK_START;
	user_tasks[2].psp_value = T2_STACK_START;
	user_tasks[3].psp_value = T3_STACK_START;
	user_tasks[4].psp_value = T4_STACK_START;


	user_tasks[0].task_handler = idle_handler;
	user_tasks[1].task_handler = task1_handler;
	user_tasks[2].task_handler = task2_handler;
	user_tasks[3].task_handler = task3_handler;
	user_tasks[4].task_handler = task4_handler;

	uint32_t *pPSP;

	for(int i = 0; i < MAX_TASKS; i++){
		pPSP = (uint32_t*)user_tasks[i].psp_value;
		pPSP--;
		*pPSP = DUMMY_XPSR;

		pPSP--; //PC
		*pPSP = (uint32_t)user_tasks[i].task_handler;

		pPSP--; //LR
		*pPSP = 0xFFFFFFFD;

		for(int j = 0; j < 13; j++){
			pPSP--;
			*pPSP = 0;
		}
		user_tasks[i].psp_value = (uint32_t)pPSP;
	}
}


uint32_t get_psp_value(void){
	return user_tasks[current_task].psp_value;
}


void update_next_task(){
	int state = TASK_BLOCKED_STATE;

	for(int i = 0; i < MAX_TASKS; i++){
		current_task++;
		current_task %= MAX_TASKS;
		state = user_tasks[current_task].current_state;
		if((state == TASK_READY_STATE) && (current_task != 0))
			break;
	}

	if(state != TASK_READY_STATE)
		current_task = 0;
}


__attribute__((naked)) void switch_sp_to_psp(void){
	// 1.
	__asm volatile("PUSH {LR}");
	__asm volatile("BL get_psp_value");
	__asm volatile("MSR PSP,R0");
	__asm volatile("POP {LR}");

	// 2.
	__asm volatile("MOV R0,#0x02");
	__asm volatile("MSR CONTROL,R0");
	__asm volatile("BX LR");
}


void enable_processor_faults(){
	uint32_t *pSHCRS = (uint32_t*)0xE000ED24;
	*pSHCRS |= (1 << 16);
	*pSHCRS |= (1 << 17);
	*pSHCRS |= (1 << 18);
}


void save_psp_value(uint32_t current_psp_value){
	user_tasks[current_task].psp_value = current_psp_value;
}


void schedule(void){
	uint32_t* pICSR = (uint32_t*)0xE000ED04;
	*pICSR |= (1 << 28);
}


void task_delay(uint32_t tick_count){
	if(current_task){
		user_tasks[current_task].block_count = tick_count + g_tick_count;
		user_tasks[current_task].current_state = TASK_BLOCKED_STATE;
		schedule();
	}
}


__attribute__((naked)) void PendSV_Handler(void){
	// save the context of the current task
		// 1. get current running task psp value
		__asm volatile("MRS R0,PSP");
		// 2. Using that psp value store SF2(r4-r11)
		__asm volatile("STMDB R0!,{R4-R11}");

		__asm volatile("PUSH {LR}");
		// 3. Save the current value of PSP
		__asm volatile("BL save_psp_value");


		// retrieve the context of next task
		// 1. Decide next task to run
		__asm volatile("BL update_next_task");
		// 2. gets its past PSP value
		__asm volatile("BL get_psp_value");
		// 3. using that psp value to retrieve SF2
		__asm volatile("LDMIA R0!,{R4-R11}");
		// 4. update psp and leave
		__asm volatile("MSR PSP,R0");


		__asm volatile("POP {LR}");

		__asm volatile("BX LR");
}


void update_global_tick_count(void){
	g_tick_count++;
}


void unblock_tasks(void){
	for(int i = 1; i < MAX_TASKS; i++){
		if(user_tasks[i].current_state != TASK_READY_STATE){
			if(user_tasks[i].block_count == g_tick_count){
				user_tasks[i].current_state = TASK_READY_STATE;
			}
		}
	}
}


void SysTick_Handler(void){

	uint32_t* pICSR = (uint32_t*)0xE000ED04;

	update_global_tick_count();
	unblock_tasks();

	*pICSR |= (1 << 28);
}


void HardFault_Handler(void){
	printf("Exception: Hard fault!\n");
	while(1);
}


void MemManage_Handler(void){
	printf("Exception: MemManage!\n");
	while(1);
}


void BusFault_Handler(void){
	printf("Exception: BusFault!\n");
	while(1);
}
