/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
	uint32_t* RCC_AHB1_ENABLE = (uint32_t*)(0x40023800 + 0x30);
	(*RCC_AHB1_ENABLE) |= 0x1;

	uint32_t* GPIO_A_OUTPUT_MODE = (uint32_t*)0x40020000;
	(*GPIO_A_OUTPUT_MODE) |= (0x1 << 10);
	(*GPIO_A_OUTPUT_MODE) &= ~(0x1 << 11);

	uint32_t* GPIO_A_OUTPUT_VALUE = (uint32_t*)0x40020014;
	(*GPIO_A_OUTPUT_VALUE) |= (1 << 5);
    /* Loop forever */
	for(;;);
}
