/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2024 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */

#include <stdint.h>
#include "main.h"

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

int main(void)
{
    /* Loop forever */
	RCC_AHB1ENR_t *RCC_AHB1ENR = (RCC_AHB1ENR_t*)(0x40023800 +  0x30);
	GPIOx_MODER_t *GPIOA_MODER = (GPIOx_MODER_t*)0x40020000;
	GPIOx_ODR_t *GPIOA_ODR = (GPIOx_ODR_t*)(0x40020000 + 0x14);

	RCC_AHB1ENR->gpioa_en = 1;
	GPIOA_MODER->moder5 = 0;
	GPIOA_MODER->moder5 = 1;

	while(1){
		GPIOA_ODR->odr5 = 1;
		for(int i = 0; i < 90000; i++){

		}
		GPIOA_ODR->odr5 = 0;
		for(int i = 0; i < 90000; i++){

		}
	}
}
